server.port=8010
spring.application.name=payment-agent

spring.ai.openai.api-key=${OPENROUTER_API_KEY:}

spring.ai.openai.base-url= https://openrouter.ai/api/v1

spring.ai.openai.chat.options.model=openrouter/free

spring.ai.mcp.client.enabled= true
spring.ai.mcp.server.expose-mcp-client-tools=true